spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devmate
    username: root
    password: 1004
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "devmate-secret-key-change-this-in-real"
  access-exp-min: 15
  refresh-exp-days: 7
